[build-system]
    requires = ["scikit-build-core", "nanobind"]
    build-backend = "scikit_build_core.build"

[project]
    name = "allpay"
    version = "0.1.0"

[dependency-groups]
    tests = ["pytest"]
    app = ["dash", "dash-cytoscape"]
    analysis = ["numpy", "matplotlib", "seaborn", "networkx"]
    all = [
        { include-group = "tests" },
        { include-group = "app" },
        { include-group = "analysis" },
    ]
