CURRENT_NODE = "current-node"
MODE = "mode"
AUCTION = "auction"
PHASE = "phase"
P1_BUDGET = "p1-budget"
P2_BUDGET = "p2-budget"
P1_BID_VALUE = "p1-bid-val"
WINNER = "winner"
LAST_P1_BID = "last-p1-bid"
LAST_P2_BID = "last-p2-bid"
GRAPH_REFRESH_DUMMY = "graph-refresh-dummy"
GRAPH_MIRROR_DUMMY = "graph-mirror-dummy"
NEW_GAME_TYPE = "new-game-type"
NEW_TIEBREAKER = "new-tiebreaker"

BTN_PVP = "btn-pvp"
BTN_PVA = "btn-pva"
BTN_ANALYSIS = "btn-analysis"
BTN_NEW_GAME = "btn-new-game"
BTN_POORMAN = "btn-poorman"
BTN_RICHMAN = "btn-richman"

GRAPH_LOADING = "graph-loading"
GRAPH = "graph"

ANALYSIS_PANEL = "analysis-panel"
ANALYSIS_LOADING = "analysis-loading"
ANALYSIS_CONTENT = "analysis-content"

GAME_CONTROLS = "game-controls"
P1_BUDGET_DISPLAY = "p1-budget-display"
P1_BID_INPUT = "p1-bid-input"
P1_LOCK_BTN = "p1-lock-btn"
STATUS_MSG = "status-msg"
P2_BUDGET_DISPLAY = "p2-budget-display"
P2_BID_CONTROLS = "p2-bid-controls"
P2_BID_INPUT = "p2-bid-input"
P2_LOCK_BTN = "p2-lock-btn"

ANALYSIS_CONTROLS = "analysis-controls"
ANALYSIS_P1_INPUT = "analysis-p1-input"
ANALYSIS_P2_INPUT = "analysis-p2-input"

GAME_MODAL = "game-modal"
BTN_TOW = "btn-tow"
BTN_RACE = "btn-race"
TOW_PARAMS = "tow-params"
RACE_PARAMS = "race-params"
TOW_LENGTH_INPUT = "tow-n-input"
RACE_A_INPUT = "race-a-input"
RACE_B_INPUT = "race-b-input"
BTN_TIEBREAKER_P1 = "btn-tb-p1"
BTN_TIEBREAKER_P2 = "btn-tb-p2"
NEW_P1_BUDGET = "new-p1-budget"
NEW_P2_BUDGET = "new-p2-budget"
BTN_CANCEL_GAME = "btn-cancel-game"
BTN_START_GAME = "btn-start-game"
